extends: airbnb
env:
  es6: true
  node: true
  browser: true
globals:
  __DEV__: true
ecmaFeatures:
  jsx: true
  modules: true
  destructuring: true
  classes: true
  forOf: true
  blockBindings: true
  arrowFunctions: true
  experimentalObjectRestSpread: true
parser: babel-eslint
parserOptions:
  sourceType: 'module'
plugins:
  - react
